services:
  mysql:
    image: mysql:8.1
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=quarkus
      - MYSQL_ROOT_PASSWORD=root
    #    ports:
    #      - 33306:3306
    volumes:
      - data:/var/lib/mysql
      - ./src/main/resources/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    container_name: code-with-quarkus
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=mysql://mysql:3306/quarkus
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data:
