DROP SCHEMA IF EXISTS quarkus;
CREATE SCHEMA quarkus;
USE quarkus;

CREATE TABLE tb_account_quarkus (
  id BIGINT NOT NULL AUTO_INCREMENT,
  ACCOUNT_USERNAME VARCHAR(40) UNIQUE,
  ACCOUNT_PASSWORD VARCHAR(40),
  PRIMARY KEY (id)
);

CREATE TABLE tb_user_quarkus (
  id BIGINT NOT NULL AUTO_INCREMENT,
  USER_ACCOUNT BIGINT NOT NULL,
  USER_NOME VARCHAR(40),
  USER_COGNOME VARCHAR(40),
  PRIMARY KEY (id),
  CONSTRAINT user_account
    FOREIGN KEY (USER_ACCOUNT)
    REFERENCES tb_account_quarkus (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);