version: '3.8'

services:
  dynamic-mock:
    image: davidedinnocente/dynamic-mock:1.0.0
    container_name: mms-mock-api
    ports:
      - "8082:8080"
    environment:
      # Indichiamo all'app dove trovare il file all'interno del container
      - MOCK_ROUTES_FILE=/app/config/routes.json
      - MOCK_TOKEN_REGEX=.*token.*
      - MOCK_JWT_PRIVATE_KEY=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHqLTmnrRWErLs6OskUKErqG/ND5xOUkfFcTcAOpb2/GyP9bQgr43QcvXk1hG3/t826ovGHTLqvI57WjN7E25bR4yTvw9IO+JyzL244S7FPq6CGI/OdPosUlPC9LXi1GIzMAsrAznnHoBwW4lxh+syFd+ACyzmkKDIrBSducwkiAUR9qHQou9saXP5oPD5BOO8AJGeaPDf7GkxhrSpzMypfDniA0M4m0pPAXyk6XTVeQ9hfPHccV6rettexYgzYi6h7LS5haKhiR0n4bsks5H+GBECRWx+vE+uEtkDnVW0djlT7Bmf5+7peTXMGvM1oU2XzFN1JEc+qdeP8tMB5EbNAgMBAAECggEAD9OMGBN19N8GvwKdMF580WwIsAmf/fxbMz0sxdr0awUU1O9+H7DSw2EizojNKZeC2Zn2H5Y3xPAn34LFqGigpjcnH0df6ShSuaoIPZlfSU7VQJDnsKRIorlEPvoCA0Y1t4bZfRzEcFEpugj40t6aMo5AeRL0XvK8Gqll+UpdnSU616njV9SQ2f8ekNMEksC6Q3JGCl0bMngzz3pbt3BFDxoGPmUUMFxriFhoMdaxRoMPJO+IRbxnvNonYumho5FHGGbGyGDUuVrCV7v4sGJ+c+FgU4e+tTWYtqeCcXahnIyGzn1YQnpxSdJhKQWRrDSIX4W3wh/Jk1/9wzs81Si1+QKBgQDX5I02vixTWsEIlq5rlLG6p6SvGAuTxkQM+XgF03gqdE23aJsGVVyYNN42AjgMLo1XXeglCP1hjaiZxc9TPWtu+1pqAcMEZVxallDwLJUaqJDmaIvWaduWm03aEF326owvfrXzwYGXzeZ1XjJrajR5mxq/khp/5lngafdInD/fGQKBgQDswBuinXrG7iyj2LYxN+StIE6ndANtNfDFIhdWl788hdr8QTR/wQLePBgOBb7A8ABa2Sn2GKC7MGm8dX4Kr6OCK6Od3UKPzbmie/dHyI9W4LZk6hZRRzBepoikDF0imh+N4yZmM/I+C2fUomuP0VQWEDY8LqeMNeAaiT4gKSy/1QKBgDV+pVsOLk+NKk2lgJyZoJxek9jq/VtlglEws4PGDX1/ig5LNjaQijwQxYrea+Lg2hbu5uneW2KDxmYr9J5slqVOVO31d8wsDYFIw89vTJbpc9YTy6qaWlXsL5M8APyAy7GtFQrMRP9HfrZQW+/vxgbn3u3fFv/gJR8NQr/UL6NpAoGAKSZO51nV4EO/kI73Q+DCJ3FJGoPooI/SlIETa2Kew6dEY7n1pQroM7ZgO/e1qxVMCn5ac8LeFQsaJb6KNNNIaTSqkKLHkfUhAePoHBr5BxGxwiKJ1IC6IIlzkIfxnDULrP7BStxWi4AyANxmM64fnmIc+yLkzlMC67nVCYP+mi0CgYEAu4z674Zl4G8xW4EmOcUUoKkJkhYf+ZlwAzlWqWBkOknMeezU7WY8HSWSdCKhLAmxJ0APt15Oqd6OcbsuslKXrM+db22FSTAP7ADBwtwCII3ZEcpoGKoNMZrSsihbwZM7MdaYtHqk7fKYDBSQBy/HskPGXJkXea0j0pkMEw5D8Mc=
    volumes:
      # Montiamo il file routes.json dal tuo host al path previsto nel container in sola lettura (ro)
      - ./routes.json:/app/config/routes.json:ro
    restart: unless-stopped
    #healthcheck:
    #  # Usiamo wget in modalità "spider" (verifica solo che risponda 200 OK)
    #  # Il tuo fallback sulla root '/' o qualsiasi path restituirà HTTP 200
    #  test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/ || exit 1" ]
    #  interval: 2s
    #  timeout: 2s
    #  retries: 15