quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.quarkus.strategy=drop-and-create
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.reactive.url=mysql://127.0.0.1:3306/quarkus